# Generated by Django 5.0.3 on 2024-03-31 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_name', models.CharField(max_length=200)),
                ('land_pos', models.CharField(max_length=1000)),
                ('land_area', models.FloatField()),
                ('land_pH', models.FloatField()),
                ('land_doAm', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=200)),
                ('plant_dev', models.DecimalField(decimal_places=2, help_text='Thời gian phát triển (tháng)', max_digits=5)),
                ('plant_type', models.CharField(choices=[('0', 'Cây lương thực'), ('1', 'Cây ăn quả'), ('2', 'Cây rau củ')], max_length=1)),
                ('plant_ND', models.DecimalField(decimal_places=2, help_text='Nồng độ khoáng chất cần thiết', max_digits=5)),
                ('plant_bp', models.IntegerField(help_text='Chu kỳ bón phân (ngày)')),
                ('unit', models.CharField(default='ppm', help_text='Đơn vị đo nồng độ khoáng chất', max_length=50)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manage.land')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_name', models.CharField(max_length=200)),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('profit', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='land',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manage.season'),
        ),
    ]
