# Generated by Django 5.0.3 on 2024-04-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0002_remove_plant_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='time_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='season',
            name='time_start',
            field=models.DateField(),
        ),
    ]
