# Generated by Django 5.0.2 on 2024-04-07 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0004_product_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='thitruong',
            fields=[
                ('id_thitruong', models.AutoField(primary_key=True, serialize=False)),
                ('id_caytrong', models.CharField(max_length=10)),
                ('ten_caytrong', models.CharField(max_length=50)),
                ('ten_thitruong', models.CharField(max_length=50)),
                ('ten_nguoiban', models.CharField(max_length=50)),
                ('gia', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='thitruong_ban',
            fields=[
                ('id_thitruong', models.AutoField(primary_key=True, serialize=False)),
                ('ten_caytrong', models.CharField(max_length=50)),
                ('ten_thitruong', models.CharField(max_length=50)),
                ('gia', models.BigIntegerField(null=True)),
            ],
        ),
    ]
