# Generated by Django 5.0.2 on 2024-04-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0005_thitruong_thitruong_ban'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('hoten', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('loinhan', models.TextField()),
            ],
        ),
    ]
