# Generated by Django 5.0.3 on 2024-04-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0006_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='plant_ND',
            field=models.CharField(help_text='Nồng độ khoáng chất cần thiết', max_length=200),
        ),
    ]
