# Generated by Django 5.0.2 on 2024-04-14 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0007_alter_plant_plant_nd'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
