# Generated by Django 5.0.2 on 2024-04-14 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0015_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
