# Generated by Django 5.0.2 on 2024-04-15 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0019_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
